# Site Settings
locale                   : "en-US"
direction                : # "ltr" (default), "rtl" # set the direction of the page
title                    : "Site Title"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Isaac Kleisle-Murphy"
description              : # "Description"
url                      : "https://isaackleislemurphy.github.io"

